POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "user1@user.com",
  "password": "123"
}

###
GET http://localhost:3000/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidXNlcjFAdXNlci5jb20iLCJpYXQiOjE2NzAyNzUxMDYsImV4cCI6MTY3MDI3NTE2Nn0.uyJn_vylzDBqcUVDtNXuQcVYxEtFEsu424GwH1_nCCE